- Cargo.lock
- Cargo.toml
- Makefile
- rust/lib.rs
Basic rust implementation. Doesn't handle schema versions or parsing json schemas yet.
> feat: Implement `get_schema` in Rust

- .github/workflows/ci.yml
https://github.com/getsentry/sentry-kafka-schemas/commit/84545fef6de110ccfc8db3c4fb9cd49fd1e9f51e added something to `make lint`, and as a result the lint job in main branch timed out.
> fix(ci): Bump timeout of linter job

- python/requirements.txt
At first I thought we should not pin this version at all because surely
people will have it pinned themselves in apps, but we should at least
rqeuire a version that contains the `Required` we use.
> fix: Enforce minimum required on typing-extensions

- examples/events/1/null-tag-keys.json
- schemas/events.v1.schema.json
Not sure why this one is still happening, I thought that at some point I
did changes to Relay so it won't. In the payload i've seen there's also
no _meta. So I think this is the SDK posting garbage.
> fix: Another instance of nullable tags

- schemas/snuba-queries.v1.schema.json
I wanted to use this type in the querylog producer code in Snuba, this nested type was needed in a few places.
> feat(querylog): Generate type for where_profile

- examples/events/1/weird-transaction-source.json
- schemas/events.v1.schema.json
It appears that relay passes through garbage values, however it doesn't
make sense to rigorously validate values here either, since Snuba
doesn't rely on them.
> fix: Relax TransactionSource definition

- python/generate_python_types.py
- python/requirements-build.txt
Upstream changes have been merged and released.
jsonschema-gentypes now uses the current Python version (in our case
Python 3.8) to determine which imports to rewrite.
> ref: Bump jsonschema-gentypes

- python/requirements.txt
Because sentry uses pyyaml 5.4
> build: pyyaml>=5.4,<7.0

- examples/ingest-metrics/1/basic-counter.json
- examples/ingest-metrics/1/basic-distribution.json
- examples/ingest-metrics/1/basic-set.json
- schemas/ingest-metrics.v1.schema.json
- schemas/snuba-generic-metrics.v1.schema.json
- topics/ingest-metrics.yaml
ingest-metrics is technically two topics, but Relay treats it as one. The messages are shaped exactly the same.
> feat: Add ingest-metrics topic

- CODEOWNERS
- README.md
- python/tests/test_codeowner.py
All topics, schemas, examples have defined codeowners. This is validated in CI for all topics.
> feat: Schema ownership

- .craft.yml
- Cargo.toml
- scripts/bump-version.sh
Bring Rust library version up to speed with current version, add crates
target to craft
Next Release will then push to crates.io
> feat: Release rust library

- schemas/subscription-results.v1.schema.json
This is never actually included in the message, only used internally in Snuba. The property is not present on the example either.
> fix: Remove incorrect property from subscription result schema

- scripts/json_schema_changes.py
The script is not supposed to print anything if there are no changes.
Instead, it prints all changed files right now, such as in https://github.com/getsentry/sentry-kafka-schemas/pull/69
Let's just get rid of filename headers for now and add them to the
"change object"
> fix: Fix filename handling of jsonschema changes

- CODEOWNERS
- examples/transactions/1/basic_insert_dev.json
- schemas/transactions.v1.schema.json
- topics/transactions.yaml
I autogenerated this from the example and it's almost certainly wrong - just a starting point we will iterate on.
Kind of wished there was an easy way to share references between topics since transactions has a fair bit of overlap with events.
> feat: Transactions topic and schema definition

- schemas/ingest-metrics.v1.schema.json
- schemas/snuba-generic-metrics.v1.schema.json
- schemas/snuba-metrics.v1.schema.json
The array of numbers can only ever be an array of u32s as per Relay
sourcecode. It is used for sets
> fix: Fix metric value types across all schemas

- .github/workflows/schema-changes.yml
The binary cache was not actually kicking in for new PRs because those
PRs can only access cache artifacts from main. But main didn't run this
workflow.
> fix: Make schema-changes workflow faster

- schemas/snuba-generic-metrics.v1.schema.json
- schemas/snuba-metrics.v1.schema.json
We are getting type-checking errors in https://github.com/getsentry/sentry/pull/46782, because
```
src/sentry/sentry_metrics/consumers/indexer/batch.py:383: error: Incompatible types (expression has type "Union[float, List[int], List[Union[int, float]]]", TypedDict item "value" has type "Union[int, float, List[int]]")  [typeddict-item]
```
This is because `List[int]` can't be cast to `Lint[Union[float, int]]`.
We should just reuse the definition sometime, but for now let's
copypaste.
> fix: Align snuba-metric value field with ingest-metrics

- .github/workflows/ci.yml
This job is currently by far the slowest one. We can reduce CI times by
quite a lot by caching Rust downloads and build artifacts
Copied from https://github.com/actions/cache/blob/main/examples.md#rust---cargo
> feat: Add Rust build cache to reduce CI times

- schemas/transactions.v1.schema.json
Eventually we want to loosen this schema quite a bit more to the minimal set of expecations the consumer has, for now just loosen a few restrictions that were not correct.
> ref: Loosen transaction schema

- CODEOWNERS
- examples/subscription-results/1/subscription-results-legacy.json
- examples/subscription-results/1/subscription-results.json
- schemas/subscription-results.v1.schema.json
Whilst creating this schema and integrating it into Snuba and Sentry we discovered there were some fields ("profile" and "trace_output") being published that were essentially internal Snuba data and are completely unused by Sentry in the results consumer. Let's remove them from the schema and example.
Since "additionalProperties" is true, this is a backward compatible change and old messages still in the pipeline will not fail validation.
> feat: Remove unused fields from subscription results

- rust/lib.rs
This is just a rudimentary impl to satisfy some traits relay requires
> fix: Impl std::error::Error for SchemaError

- Cargo.toml
- rust/build.rs
Relay currently does not use those generated types, and there were
concerns about bloated dependency tree.
> fix: Make generated schema types an optional feature

- Cargo.toml
The dependency is only imported from within generated code.
> fix(rust): Make regress dependency optional as well

- examples/events/1/tombstone-events-no-datetime.json
- schemas/events.v1.schema.json
I'm actually a bit confused by some of the other example tombstone events already checked in here because it doesn't look like Sentry is ever sending this
https://github.com/getsentry/sentry/blob/34a6dde71ea2f43c39ebc370e94692ca5e50555b/src/sentry/eventstream/snuba.py#L345-L351
> fix(events): Fix the schema for tombstone events

- schemas/transactions.v1.schema.json
We don't want to be overly strict. If no consumer requires some invariant we are not going to enforce it here.
There's a lot more that can be loosened here, this is just some stuff I saw regularly happenening today.
> fix(transactions): Remove some stuff Snuba doesn't care about

- examples/snuba-generic-metrics/1/snuba-generic-metrics1.json
- examples/snuba-metrics/1/snuba-metrics1.json
- schemas/snuba-generic-metrics.v1.schema.json
- schemas/snuba-metrics.v1.schema.json
Supporting the work started here: https://github.com/getsentry/sentry/pull/47577. 
If we change the name of the field in the above PR, will make corresponding changes here as well.
> feat(metrics): Add sentry_received_timestamp to schemas to support indexer SLO

- schemas/snuba-generic-metrics.v1.schema.json
- schemas/snuba-metrics.v1.schema.json
We decided to be less strict across the board and allow `additionalProperties=true` everywhere so messages won't fail schema validation if they are unlikely to crash consumers. This updates the metrics and generic metrics schemas to allow additional properties.
> fix: Loosen metrics schemas

- schemas/events.v1.schema.json
With subdivision is stored (https://github.com/getsentry/relay/pull/2058), this PR is updating the event schema to include it in the `geo` data.
> feat(geo): Add subdivision to event schema

- schemas/events.v1.schema.json
"old_primary_hash" can be null
> fix(events): Fix schema for tombstone event

- .github/workflows/build.yml
- setup.py
https://github.com/getsentry/pypi/pull/289 was never merged because the produced wheel is junk, because the `codecs` module was not declared in setup.py. Fix that and add CI to prevent that from happening again.
> fix(build): Add missing module to setup.py

- README.md
- python/sentry_kafka_schemas/codecs/__init__.py
- python/sentry_kafka_schemas/codecs/json.py
- python/sentry_kafka_schemas/codecs/msgpack.py
I noticed we didn't have any docs on how to actually use schemas. Add a
simple example that uses both Python types and codecs at once.
Also make the validate parameter default to true in codecs.
> fix(doc): Document how to use a schema

- python/sentry_kafka_schemas/codecs/json.py
- python/sentry_kafka_schemas/codecs/msgpack.py
Schema is optional in the JsonCodec and MsgpackCodec. So they can be used for topics where a schema isn't defined yet. Otherwise a separate codec will need to be defined for all topics which don't have a schema, which is a pain for users.
This is the same as the Arroyo implementation does.
> feat: JsonCodec and MsgpackCodec are usable without schemas

- python/sentry_kafka_schemas/codecs/__init__.py
I didn't realize the entire time that that method was not on the
baseclass. It is useful because currently we are treating validation
errors as just warnings, meaning that we need to decode even if
validation fails.
We already effectively used arroyo codecs this way.
> fix: Make Codec.validate public

- .github/workflows/schema-changes.yml
- schemas/events.v1.schema.json
- scripts/json_schema_changes.py
Printing a codeblock is kind of ugly -- let's try markdown lists
> fix: Improve formatting of schema diff further

- scripts/json_schema_changes.py
https://github.com/getsentry/sentry-kafka-schemas/pull/132 shows that
there is a legitimate usecase for breaking changes in the schema: When
the schema is just plain wrong and the consumer would already crash on
those now-invalid messages today.
> fix: Adjust breaking changes warning

- schemas/transactions.v1.schema.json
As per https://github.com/getsentry/snuba/blob/68172ab32529364c912efd4da26b85d85ac47389/snuba/datasets/processors/spans_processor.py#L402, parent_span_id can be null, and it is also not required.
> fix(transactions): Fix parent-span-id

- schemas/transactions.v1.schema.json
Snuba spans processor only uses the value and ignores the unit https://github.com/getsentry/snuba/blob/68172ab32529364c912efd4da26b85d85ac47389/snuba/datasets/processors/spans_processor.py#L215-L244
Also needed for https://github.com/getsentry/sentry/pull/48670
> fix(transactions): measurement.unit is not required

- topics/ingest-replay-recordings.yaml
I believe this is a Sentry consumer, not Snuba
> fix(ingest-replay-recordings): Fix consumer service

- schemas/transactions.v1.schema.json
Neither the Snuba transactions or spans consumers require these fields.
Needed for https://github.com/getsentry/sentry/pull/48670
> fix(transactions): Remove properties incorrectly set to required in trace context

- schemas/transactions.v1.schema.json
Null is allowed as a tag entry
> fix(transactions): Standardise tags in transactions to match events

- schemas/events.v1.schema.json
Remove all the properties except those that Snuba cares about (headers, url, method). Being too strict can cause unnecessary schema validation failures. In this case the "data" did not always match the values we saw in prod.
> feat: Loosen requests in events schema

- README.md
- schemas/transactions.v1.schema.json
Add spans data schema. This can help us validate messages in the spans data bag.
Also:
* Fixed typo in the readme
* Add title to the top level transaction message
> Add spans data schema

- CODEOWNERS
- examples/generic-events/1/insert.json
- topics/generic-events.yaml
Currently this points at the same schema as "events". Though technically there are only inserts on this topic and not replacements.
> feat: Add generic-events topic

- examples/generic-events/1/insert.json
- schemas/generic-events.v1.schema.json
- topics/generic-events.yaml
The example introduced in https://github.com/getsentry/sentry-kafka-schemas/pull/154 was wrong. Generic events needs "occurrence_id" and "occurrence_data".
Created a separate schema for generic-events. It's similar to events with these differences:
- occurrence_id
- occurrence_data
- only inserts, no replacement types
> feat(generic-events): Fix schema and example

- schemas/ingest-replay-events.v1.schema.json
Consumer pulls type out of the deserialized payload, it's not a required top level property and is not always being populated. ref: https://github.com/getsentry/snuba/blob/dea5838d3cffe3dfaeed0ab5c956f7b578affd1a/snuba/datasets/processors/replays_processor.py#L178-L192
> fix(ingest-replay-events): Type is not required

- .gitignore
- CODEOWNERS
- examples/group-attributes/1/assignee_changed.json
- examples/group-attributes/1/group_created.json
- examples/group-attributes/1/group_deleted.json
- examples/group-attributes/1/owner_changed.json
- schemas/group-attributes.v1.schema.json
- topics/group-attributes.yaml
Define a new message type for replicating a subset of attributes from the Group, GroupAssignee, and GroupOwner postgres tables to snuba.
> feat(group-attributes): add new topic and schema for group attributes

- schemas/snuba-queries.v1.schema.json
These are always present and are required since https://github.com/getsentry/snuba/pull/4511
> feat: Mark required fields in querylog

- schemas/snuba-generic-metrics.v1.schema.json
Adding an optional field `aggregation_option` to metric messages so each message can encode special aggregation that needs to be performed on it.
For instance, an `aggregation_option` may be `STD_HIST`, this indicate to the snuba consumer to set the `enable_histogram` field to `1` so that histogram aggregation can be applied.
> feat(generic-metrics): Add `aggregation_option` field to metrics

- schemas/snuba-queries.v1.schema.json
We are currently porting the querylog processor from Python to Rust, and checking the codebase to figure out what these types were supposed to be was very tricky. Let's add them to the schema.
> feat(querylog): Add schema definition for stats object

- schemas/events.v1.schema.json
Avoid unnecessary validation failures since Snuba does nothing with these fields
> fix: Simplify events schema

- examples/snuba-spans/1/basic_span.json
- schemas/snuba-spans.v1.schema.json
Fixes a bug where the span message type was an array. It should just be a an object.
> fix(spans): remove array type

- README.md
- schemas/transactions.v1.schema.json
This reverts commit d288a50e9447650067d914f37cf964a2ed68839c.
This was added because spans was part of transactions in the initial implementation. It is a separate topic now.
This schema seems to be causing issues in prod since not all transactions events actually conform to it.
> Revert "Add spans data schema (#153)"

- schemas/events.v1.schema.json
- schemas/generic-events.v1.schema.json
Prerequisite for https://github.com/getsentry/sentry/pull/55135 (Network Error Logging).
No extra validation yet (I don't see any extra validation for `csp` either). This should unblock local testing etc.
> Allow new `nel` event type in events topics

- schemas/snuba-spans.v1.schema.json
We're expecting an object at a time, not an array of spans.
> fix(spans): Remove wrong array type

- schemas/events.v1.schema.json
- schemas/generic-events.v1.schema.json
- Adds the feedback event type. See https://github.com/getsentry/team-replay/issues/222
- We'll be leveraging the issue platform to create issues, and these feedbacks will flow in from relay on the events topic and be picked up in the ingest consumer and have issues created via issue platform, which is why we need the event type on both.
> feat(feedback): add feedback as new event type

- examples/snuba-generic-metrics/1/snuba-generic-metrics-gauge.json
- schemas/ingest-metrics.v1.schema.json
- schemas/snuba-generic-metrics.v1.schema.json
Schema representing the 5 expected values of a `Gauge`
> Add gauges to ingest + snuba generic metrics schema

- rust/build.rs
Previously, cargo would unconditionally rebuild the crate (and all its dependants) because "the file `…/sentry-kafka-schemas/build.rs` is missing"
> Avoid reruns of the build script

- Cargo.toml
- rust/build.rs
- rust/lib.rs
This embeds all the example data in the built Rust crate, and adds a new `examples()` method on `Schema` to expose that to consuming Rust code.
> Embed and expose examples in Rust

- CODEOWNERS
- README.md
Pierre should not be blocked on changes to the schema, he sufficiently
owns both ends of the pipe
> ref: Add more codeowners

- rust/build.rs
- rust/lib.rs
In code generation, we create a sorted list of topics called TOPICS
containing key-value pairs, and then later use binary search to find an
entry by key. We don't use maps because those cannot be created at compile
time, only arrays.
Unfortunately we used a different key in each process. So we sorted by a
value like "transactions.yaml" when creating the list, but the row reads
like this:
[
...
("transactions", "<yaml contents>"),
so the lookup happens on a value like "transactions". This is not a big
difference, but it matters because we also have
"transactions-subscription-results", which sorts after "transactions",
but before "transactions.yaml"
Refactor the build.rs so that a consistent sorting order is used, and
add a test for "tranasctions" specifically which previously would always …
> fix(rust): Fix spurious topic-not-found due to wrong sorting key

- rust/build.rs
- rust/lib.rs
This came up in https://github.com/getsentry/snuba/pull/5451 where I had
to approve a ton of snapshot tests, because the examples there got
reordered. I want to name those snapshot files after the filename in
sentry-kafka-schemas (instead of an integer) so this is easier to debug.
> ref(rust): Add example name to examples

- schemas/ingest-replay-recordings.v1.schema.json
We're now sending the replay_event to the recording consumer on an optional key. Produced in https://github.com/getsentry/relay/pull/3035, recording consumer change forthcoming
> feat(replays): add replay event to recording schema

- schemas/ingest-replay-recordings.v1.schema.json
VSCode insisted on auto-formatting and I'm too tired to argue with it anymore.  The only change is the replay-video field.
> feat(replays): Add replay-video attribute to recording message

- .github/workflows/build.yml
- .github/workflows/ci.yml
- .github/workflows/docs.yml
- .github/workflows/schema-changes.yml
- python/requirements-build.txt
- schemas/events.v1.schema.json
- scripts/json_schema_changes.py
The current errors schema from Relay is overly complicated. Let's use
the generated one from Snuba and see if it passes schema validation too.
Intentionally punting on a solution for keeping the schemas in sync --
we have tests in Snuba for that which currently fail, because Relay's
schema is too complex to be compared using json-schema-diff.
> ref: Import errors schema from Snuba

- schemas/ingest-metrics.v1.schema.json
The indexer does not care about what the value field is, the validation for value should happen further down the pipeline. Updates the schema to remove value field constraints.
> perf(gen-metrics): Remove value validation for indexer schema

- schemas/events.v1.schema.json
I forgot to export a significant amount of Python types using "title",
and also accidentally made the typing for replacements a lot weaker.
> fix: Fix errors schema again

- CODEOWNERS
This project is imported by ops for kafka control plane now as prod config will be sync with it. team-ops should be owners too.
> ref: Add team ops as codeowners

- python/tests/test_sentry_kafka_schemas.py
- topics/ingest-events-dlq.yaml
- topics/ingest-generic-metrics-dlq.yaml
- topics/ingest-metrics-dlq.yaml
- topics/snuba-dead-letter-generic-metrics.yaml
- topics/snuba-dead-letter-group-attributes.yaml
- topics/snuba-dead-letter-metrics.yaml
- topics/snuba-dead-letter-querylog.yaml
- topics/snuba-dead-letter-replays.yaml
DLQ retention is one week. This matches what we do across all DLQ topics in Sentry prod.
> feat: Add retention values to DLQ

- CODEOWNERS
The `owners-ingest` group was renamed a while back and does not exist anymore.
Also moved snuba to the front to have it better aligned with the other entries.
> meta: fix ingest code owners

- topics/events.yaml
- topics/transactions.yaml
This value seems extaordinarily large to me, but it's what we have in production today so 🤷
> feat: Add max.message.bytes on events and transactions topics

- topics/ingest-attachments-dlq.yaml
- topics/ingest-events-dlq.yaml
- topics/ingest-feedback-events-dlq.yaml
- topics/ingest-generic-metrics-dlq.yaml
- topics/ingest-metrics-dlq.yaml
- topics/ingest-transactions-dlq.yaml
- topics/snuba-dead-letter-generic-metrics.yaml
- topics/snuba-dead-letter-group-attributes.yaml
- topics/snuba-dead-letter-metrics.yaml
- topics/snuba-dead-letter-querylog.yaml
- topics/snuba-dead-letter-replays.yaml
should be `retention.ms` not `log.retention.minutes` which is a cluster wide setting and can't be passed for topic creation config.
> fix: Fix topic creation config

- CODEOWNERS
- topics/buffered-segments-dlq.yaml
Adds buffered-segments-dlq
The [topic](https://github.com/getsentry/ops/blob/f451d30a5dfe06bf20aec111023f2c28a9983b18/k8s/services/topicctl/_values.yaml#L20) was already added as a part of the span only perf issue detection pipeline
Adding the schemas, adding it to the consumers
> feat: Add a DLQ for buffered segment topic

- examples/ingest-metrics/1/base64-dist.json
- examples/ingest-metrics/1/base64-set.json
- examples/snuba-generic-metrics/1/snuba-generic-metrics-dist-base64.json
- examples/snuba-generic-metrics/1/snuba-generic-metrics-sets-base64.json
- schemas/ingest-metrics.v1.schema.json
- schemas/snuba-generic-metrics.v1.schema.json
Reverts getsentry/sentry-kafka-schemas#255
> feat(generic-metrics): Redo Add base64 support to metrics schemas

- schemas/ingest-monitors.v1.schema.json
It seems sometimes this will not be set by relay see [0].
[0]: https://github.com/getsentry/relay/blob/4cb86c9c7f636157dd185107569cb521de40d192/relay-server/src/services/store.rs#L1531
Fixes [SENTRY-38FS](https://sentry.sentry.io/issues/5256667522/)
> ref(crons): Allow null for sdk property

- Cargo.toml
previous version of typify doesn't seem to work with the rust version running in github actions
> fix: Upgrade typify to unblock CI

- topics/ingest-feedback-events-dlq.yaml
Needs to match the underlying ingest-feedback-events topic
Needs https://github.com/getsentry/sentry-kafka-schemas/pull/261
> fix: ingest-feedback-events-dlq max.message.bytes

- examples/ingest-replay-events/1/click-serialized.json
- schemas/ingest-replay-events.v1.schema.json
Previously, we were using a unoptimized data structure. This change makes sure that we don't break production and also make the transition to a better one.
Ref: https://github.com/getsentry/snuba/pull/5831
Ref: https://github.com/getsentry/sentry/pull/69916
> perf: change payload type of replay event

- schemas/group-attributes.v1.schema.json
We're adding a new column for group_priority to the GroupAttributes table in https://github.com/getsentry/snuba/pull/5786. This updates the kafka schema to support the new field.
> Add priority to group attributes schema

- examples/ingest-metrics/1/base64-set.json
- examples/snuba-generic-metrics/1/snuba-generic-metrics-sets-base64.json
Since we're moving to using the non-padded version, we need to adjust the Kafka schema examples accordingly to generate snapshots in Snuba. 
The Rust consumers are evaluated against these examples in the Snuba test suite.
> feat(generic-metrics): Switch Kafka schema examples to non-padded Base64 encoding

- examples/monitors-clock-tasks/1/mark_timeout.json
- schemas/monitors-clock-tasks.v1.schema.json
We're going to use this to group tasks in the task consumer, so we need
it to be part of all messages
> feat(crons): Ensure monitor_environment_id in all clock tasks

- topics/buffered-segments.yaml
We're hitting some max message size limits while producing to this topic. We expect this payload to be around sizes we see on transactions. Not quite bumping it to 25 MB yet (that's what transactions has), want to see how far 10 MB gets us
> feat: Update max message size on buffered-spans

- CODEOWNERS
- topics/event-replacements.yaml
Needs to be here for kafka control plane, as these will be used to generate production configs in ops.
Ideally this would have a more defined schema + examples.
> feat: Add missing event-replacements topic

- schemas/ingest-metrics.v1.schema.json
This PR adds the `received_at` field to the Kafka schema for metrics produced by Relay.
Related to: https://github.com/getsentry/relay/pull/3561
> feat(metrics): Add received_at timestamp to Kafka schema

- examples/ingest-metrics/1/zstd-dist.json
- examples/ingest-metrics/1/zstd-set.json
- examples/snuba-generic-metrics/1/snuba-generic-metrics-dist-zstd.json
- examples/snuba-generic-metrics/1/snuba-generic-metrics-sets-zstd.json
- schemas/ingest-metrics.v1.schema.json
- schemas/snuba-generic-metrics.v1.schema.json
The last (and possibly most important) step of bucket encoding and compression. Adding actual compression support to the schema.
> feat(generic-metrics): Add support for zstd compression in message processing

- topics/ingest-events-dlq.yaml
- topics/ingest-transactions-dlq.yaml
this should match message size on the underlying topics they are dlq for
> fix: max.message.bytes for dlq topics

- topics/snuba-dead-letter-metrics.yaml
- topics/snuba-metrics.yaml
this reflects what we have in production, all definitions should align
> set max message bytes on snuba-metrics and snuba-dead-letter-metrics to 10mb

- CODEOWNERS
According to https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners#codeowners-syntax
```
If the code owners are not on the same line, the pattern matches only the last mentioned code owner.
```
So, in order to have specific owners for specific files, the broader rules need to the at the top.
> fix: Move default rule to the top of the file

- schemas/snuba-spans.v1.schema.json
I also retracted the previous release introducing the fields.
https://github.com/getsentry/publish/issues/3862#issuecomment-2115517847
> fix(spans): Fix timestamp names to reflect better their use

- topics/monitors-clock-tick.yaml
Adding this here ensures it will be enforced in ops CI
> monitors-clock-tick must always have 1 partition

- topics/ingest-monitors.yaml
this does not currently match actual config at sentry. we don't set this in production so it shouldn't be here.
> fix: ingest-monitors topic configuration

- topics/ingest-replay-events.yaml
this does not match the value in sentry prod, they should align, and this will be validated by CI soon.
https://github.com/getsentry/ops/blob/4b204b222bebc275726a638618eb0e318970da7f/k8s/services/topicctl/_values.yaml#L93
> fix max.message.bytes on ingest-replay-events

- topics/snuba-spans.yaml
we have 10mb set in production, let's also enforce that here as spans messages can be larger
> fix snuba-spans max.message.bytes

- python/tests/test_sentry_kafka_schemas.py
- topics/snuba-metrics-summaries.yaml
- topics/snuba-queries.yaml
- topics/snuba-spans.yaml
this matches what we have set in sentry prod, these were incorrectly omitted here earlier
> fix message.timestamp.type on 3 topics

- topics/processed-profiles.yaml
- topics/profiles-call-tree.yaml
this seems ginormous but it matches what is defined in prod
> processed-profiles and profiles-call-tree have 50mb

- python/sentry_kafka_schemas/sentry_kafka_schemas.py
- python/tests/test_sentry_kafka_schemas.py
- topics/monitors-clock-tick.yaml
- topics/snuba-commit-log.yaml
- topics/snuba-generic-events-commit-log.yaml
- topics/snuba-generic-metrics-counters-commit-log.yaml
- topics/snuba-generic-metrics-distributions-commit-log.yaml
- topics/snuba-generic-metrics-gauges-commit-log.yaml
- topics/snuba-generic-metrics-sets-commit-log.yaml
- topics/snuba-metrics-commit-log.yaml
- topics/snuba-transactions-commit-log.yaml
@evanpurkhiser pointed out the name "partitions" was misleading on https://github.com/getsentry/sentry-kafka-schemas/pull/294
> rename partitions to enforced_partition_count

- topics/ingest-metrics.yaml
- topics/ingest-performance-metrics.yaml
- topics/snuba-generic-metrics.yaml
ingest-metrics, ingest-performance-metrics and snuba-generic-metrics all have 10mb set in prod, we need to match it here
> set 10mb max.message bytes for metrics topics

- CODEOWNERS
- examples/ingest-occurrences/1/monitor-failure.json
- schemas/ingest-occurrences.v1.schema.json
- topics/ingest-occurrences.yaml
we need to add all the missing topics here so they can be used to generate topic/consumer group configuration in prod
i figured out the schema/required fields by reading the consumer code in https://github.com/getsentry/sentry/blob/671811bab8661ea5bd7c1dc95cd5bc341bf8a22d/src/sentry/issues/occurrence_consumer.py
> add schema, examples and topic definition for ingest-occurrences

- schemas/group-attributes.v1.schema.json
Update the schema to handle the new `group_first_release_id` column added to GroupAttributes in https://github.com/getsentry/snuba/pull/5986
> feat(issue-search): Add first_release_id to the group_attributes kafka schema

- examples/uptime-results/1/failure.json
- examples/uptime-results/1/succeess.json
- examples/uptime-results/1/timeout.json
- schemas/uptime-results.v1.schema.json
We don't want this system to be aware of the details of which system is consuming it, so just use a subscription id to keep track of things
> fix(uptime): Add `subscription_id` and remove monitor related ids

- schemas/group-attributes.v1.schema.json
This field was added to GroupAttributes as UUID but release IDs are bigints. We're updating the column in the table and the schema should be updated to match as well. 
The `first_release_id` field isn't populated anywhere yet so this is a safe change.
> fix(group-attributes): Update first_release_id field to integer or null

- schemas/group-attributes.v1.schema.json
Updating the name for this field to `first_release` to match the column, `GroupAttributes.group_first_release`. This field is still unused so the name change shouldn't affect any producers.
> fix(group-attributes): Update name for field to `first_release`

- python/tests/test_valid_topic_data.py
- topics/buffered-segments-dlq.yaml
- topics/ingest-attachments-dlq.yaml
- topics/ingest-generic-metrics-dlq.yaml
- topics/ingest-metrics-dlq.yaml
- topics/snuba-dead-letter-generic-metrics.yaml
- topics/snuba-dead-letter-querylog.yaml
- topics/snuba-dead-letter-replays.yaml
fix `buffered-segments-dlq`, `ingest-attachments-dlq`, `ingest-metrics-dlq` and `ingest-generic-metrics-dlq`, `snuba-dead-letter-generic-metrics`, `snuba-dead-letter-querylog`, `snuba-dead-letter-replays`
also adds a test
> ensure dlq topics have the same message size as their underlying topics

- examples/snuba-metrics/1/snuba-metrics-sampled.json
- schemas/ingest-metrics.v1.schema.json
- schemas/snuba-generic-metrics.v1.schema.json
Use floating point as weights instead of integers
> fix(generic-metrics): Use floating point as sample weight

- schemas/uptime-results.v1.schema.json
This is already always being set by the uptime checker. Correct the schema to match what we're doing
> fix(uptime): Require span_id

- Cargo.toml
Streamlines both build and runtime dependencies of the Rust crate:
- Update `jsonschema` to `0.18` and removes default features. Most notably, this
disables the `resolve-http`, which bundles `reqwest`.
- Remove `regress`, as this doesn't seem to be referenced by generated code
anymore.
- Remove `jsonschema` and `thiserror` from build dependencies, as these aren't
used.
Ideally, I would also remove the duplicated build-dependencies from dependencies
as these are all enabled by **default**. However, I wasn't sure how the build
script was intended to be used, so I left it alone.
> build(rust): Streamline dependencies

- schemas/uptime-results.v1.schema.json
Since this is now configurable via the check config.
> ref(uptime): Allow additional methods in `request_type`

- examples/uptime-configs/1/example-post.msgpack
- schemas/uptime-configs.v1.schema.json
Adds to the uptime-configs topic schema the ability to specify method, headers, and body
> feat(uptime): Add request{method,headers,body} fields

- .github/workflows/build.yml
The release action is now failing, seeing if just bumping this fixes it
> chore(github): Bump `upload-artifact` to v4

- CODEOWNERS
- examples/snuba-eap-mutations/example-1.json
- examples/snuba-eap-mutations/mutation-1.json
- schemas/snuba-eap-mutations.v1.schema.json
- topics/snuba-eap-mutations.yaml
Adds the schema, topic metadata, and an example for the new Snuba eap mutations topic
Relevant to https://github.com/getsentry/snuba/pull/6216
> feat(eap): Add EAP mutations topic

- examples/uptime-configs/1/example-post.msgpack
- schemas/uptime-configs.v1.schema.json
This allows multiple headers with the same name, as well as ordering consistencies.
> ref(uptime): Switch request_headers to a array of tuples

- examples/snuba-queries/1/snuba-queries-empty-trace-id.json
- examples/snuba-queries/1/snuba-queries1.json
- examples/snuba-queries/1/with-organization-id.json
- schemas/snuba-queries.v1.schema.json
unblocks https://github.com/getsentry/snuba/pull/6371
> Changes the schema so Querylog can use `progress_bytes` instead of `bytes`

- CODEOWNERS
- topics/eap-spans-subscription-results.yaml
- topics/scheduled-subscriptions-eap-spans.yaml
- topics/snuba-eap-spans-commit-log.yaml
These topic configurations are identical to other event type subscription topics (and are expected to be so)
> Add topic configurations required for EAP alerts

- examples/monitors-clock-tick/1/example-volume-abnormal.json
- examples/monitors-clock-tick/1/example-volume-normal.json
- schemas/monitors-clock-tick.v1.schema.json
This will be used to inform the clock tick tasks that the tick detected
an abnormal amount of check-in volume for the previous minute.
Part of https://github.com/getsentry/sentry/issues/79328
> feat(crons): Add "volume_anomaly_result" result to clock-tick

- schemas/monitors-clock-tasks.v1.schema.json
This is due to the issue https://github.com/Tencent/rapidjson/issues/2314
> fix(crons): Switch to `enum` as a shape Discriminator in clock tasks

- examples/monitors-clock-tasks/1/mark_missing_abnormal.json
- schemas/monitors-clock-tasks.v1.schema.json
When a clock tick is marked as having an abnormal volume we may have
lost check-is that should have been processed during this minute. In
this scenario we do not want to notify on misses, and instead should
create them as unknown misses.
Part of https://github.com/getsentry/sentry/issues/79328
> feat(crons): Add `volume_anomaly_result` to mark_missing task

- examples/monitors-clock-tasks/1/mark_unknown.json
- schemas/monitors-clock-tasks.v1.schema.json
This task will be triggered when we detect an anomaly in check-in
volume during a clock tick. When this happens we are unable to know that
all check-ins before that tick have been received and will need to mark
all in-progress monitors as resulting in a 'unknown' state.
Part of https://github.com/getsentry/sentry/issues/79328
> feat(crons): Add `mark_unknown` clock task

- CODEOWNERS
- examples/taskworker/1/basic.json
- schemas/taskworker.v1.schema.json
- topics/task-worker.yaml
The changes in getsentry/sentry#79742 are blocked because the `task-worker` topic does not have schema metadata.
While I would like this topic to contain protobuf messages, we lack tooling for that here at this time. As a temporary solution, I've added JSON schema for the task-worker topic, and will work on adding protobuf support separately.
> feat: Add taskworker schema

- CODEOWNERS
- examples/monitors-incident-occurrences/1/example.json
- schemas/monitors-incident-occurrences.v1.schema.json
- topics/monitors-incident-occurrences.yaml
Part of https://github.com/getsentry/sentry/issues/79328
This creates the new topic necessary for delaying issue occurrences so that we can delay creation of notifications in the case where we detect an anomalous system incident.
> feat(crons): Add monitors-incident-occurrences

- examples/monitors-clock-tick/1/example-volume-abnormal.json
- examples/monitors-clock-tick/1/example-volume-normal.json
- schemas/monitors-clock-tick.v1.schema.json
We'll no longer be passing this value through
> ref(crons): Remove unused `volume_anomaly_result` from clock_tick

- examples/monitors-clock-tasks/1/mark_missing.json
- examples/monitors-clock-tasks/1/mark_missing_abnormal.json
- schemas/monitors-clock-tasks.v1.schema.json
We'll no longer be using this, similar to GH-349.
See https://github.com/getsentry/sentry/pull/80650
> ref(crons): Remove volume_anomaly_result from mark_missing task

- schemas/uptime-configs.v1.schema.json
- adds trace_sampling as an optional boolean field on our uptime config kafka schema. part of https://github.com/getsentry/team-uptime/issues/22
> feat(uptime): add trace_sampling to kafka schema

- Cargo.toml
- python/generate_python_types.py
- python/sentry_kafka_schemas/codecs/json.py
- python/sentry_kafka_schemas/codecs/msgpack.py
- python/tests/test_examples.py
- rust/lib.rs
This allows us to reference external schemas to avoid duplication. They can be referenced like
```
"$ref": "file://uptime-results.v1.schema.json#/definitions/CheckResult"
```
The handler assumes all schemas will be located in out `schemas` directory.
Usage example here: https://github.com/getsentry/sentry-kafka-schemas/pull/361
> feat: Allow schemas to reference other schemas

- CODEOWNERS
- examples/snuba-uptime-results/1/failure.json
- examples/snuba-uptime-results/1/succeess.json
- examples/snuba-uptime-results/1/timeout.json
- rust/lib.rs
- schemas/snuba-uptime-results.v1.schema.json
- topics/snuba-uptime-results.yaml
I wanted to avoid duplication in https://github.com/getsentry/sentry-kafka-schemas/pull/359, so I wrote https://github.com/getsentry/sentry-kafka-schemas/pull/360 to allow us to reference other schemas.
> feat(uptime): new snuba-uptime-results topic

- schemas/uptime-results.v1.schema.json
Add `region` to uptime results, so that we're able to track where this result came from.
> feat(uptime): Include region in uptime results

- CODEOWNERS
- examples/snuba-ourlogs/1/maximal_log.json
- examples/snuba-ourlogs/1/minimal_log.json
- schemas/snuba-ourlogs.v1.schema.json
- topics/snuba-ourlogs.yaml
Logs are essentially spans, but without a duration
> feat: add schemas for ourlogs

- .github/workflows/ci.yml
- Cargo.toml
- rust/build.rs
- rust/lib.rs
When adding support for protocol buffer support for topic schema in #344 I only implemented python support. These changes add similar support for the rust library.
Because we effectively need to look up protobuf generated code at runtime, I expanded the scope of `build.rs` to generate `PROTOS`, which is similar to `EXAMPLES` and `TOPICS`. In order to appease the compiler, I needed to use `Box<dyn Any>` and `.downcast` into the specific structure that the consuming application needs. Obviously this parse/validate logic requires having `sentry-protos` available expanding the dependencies of this project, which could spill into consuming applications as well.
> Improve support for protocol buffer topics in rust library

- .github/workflows/docs.yml
This bumps the version for the actions that use the deprecated `upload-artifact` github action 
```
This request has been automatically failed because it uses a deprecated version of `actions/upload-artifact: v3`. Learn more: https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
> bump version

- CODEOWNERS
- topics/ingest-events-backlog.yaml
- topics/ingest-transactions-backlog.yaml
This creates the errors/events backlog topic for kafka router. This does so in all regions.
> Creating the events backlog topic

- schemas/ingest-monitors.v1.schema.json
This actually is NOT when relay kafka produces the message into kafka
(we can use the headers timestamp for that, since w're configured for
LogAppendTime)
Here's where this is actually coming from
https://github.com/getsentry/relay/blob/671bdf354b1fdc401d1a1c39430b7b1da3e70cec/relay-server/src/services/store.rs#L845
Where the `start_time` here actually comes from the managed envelope
https://github.com/getsentry/relay/blob/671bdf354b1fdc401d1a1c39430b7b1da3e70cec/relay-server/src/services/store.rs#L175
Which comes from the actual envelope store request start_time
https://github.com/getsentry/relay/blob/671bdf354b1fdc401d1a1c39430b7b1da3e70cec/relay-server/src/utils/managed_envelope.rs#L495-L500
> fix(crons): Correct description of start_time

- topics/snuba-dead-letter-generic-metrics.yaml
- topics/snuba-dead-letter-group-attributes.yaml
- topics/snuba-dead-letter-metrics.yaml
- topics/snuba-dead-letter-querylog.yaml
- topics/snuba-dead-letter-replays.yaml
we found these bugs when using this data to generate initial cluster assignments for itty-bitty
> fix incorrect pipeline annotations

- CODEOWNERS
- examples/ingest-spans/1/basic_span.json
- schemas/ingest-spans.v1.schema.json
- topics/ingest-spans.yaml
Introduces the `ingest-spans` topic and schema, which is the ingest counterpart
to `snuba-spans`. It will receive unbuffered spans directly from Relay to be
consumed by the trace buffer in Sentry.
Initially, this is a clone of the `snuba-spans` schema. Over time, the
definition will diverge, with `ingest-spans` having fewer attributes that are
not available before spans have been buffered.
This topic will not be used in production until further notice.
See https://github.com/getsentry/sentry/pull/86201
> feat: Introduce ingest-spans

- examples/snuba-spans/1/basic_span.json
- schemas/buffered-segments.v1.schema.json
- schemas/ingest-spans.v1.schema.json
- schemas/snuba-spans.v1.schema.json
Various fixes to the `ingest-spans`, `buffered-segments`, and `snuba-spans`
schema definitions:
- Remove `_metrics_summary`, as this is no longer produced and supported
- Make `parent_span_id` and `segment_id` optional everywhere
- Remove `exclusive_time_ms` from `ingest-spans` and `buffered-segments`
- Remove `is_segment` and `segment_id` from `ingest-spans`
Also exposes `SegmentSpan` as named type from `buffered-segments` for the consumer
> fix(spans): Align the spans topics with reality

- examples/snuba-spans/1/basic_span.json
- schemas/snuba-spans.v1.schema.json
Relay started sending this property in https://github.com/getsentry/relay/pull/4540. Align the schema so that Snuba's CI recognizes the field (see https://github.com/getsentry/snuba/actions/runs/14589967916/job/40923057987?pr=7108).
> feat(snuba-spans): add `kind` field

- Cargo.toml
For some reason, there was a mistake in the code generated to find a Protobuf schema in the list.
> chore: Update sentry_protos to 0.1.74

- Makefile
- rust/lib.rs
Compilation fails if default features are disabled.
This fixes the issue and also adds a check to CI.
> fix(rust): Fix compilation with no default features enabled

- CODEOWNERS
- topics/taskworker-cutover.yaml
- topics/taskworker-email-dlq.yaml
- topics/taskworker-email.yaml
This PR is responsible for creating default topics configs for taskworker-email, taskworker-email-dlq, and taskworker-cutover.
> feat(taskworker): Add taskworker email and cutover topics configs

- examples/buffered-segments/1/basic_buffered_segment.json
- schemas/buffered-segments.v1.schema.json
Adds fields that are present and required on `buffered-segments`, but have not
been included in its schema. The preceding `ingest-spans` topic already had
these fields included.
Also exposes `MeasurementValue` as a named type so we can import it in Sentry.
Ref VIEPF-5
Required by https://github.com/getsentry/sentry/pull/92185
> fix: Add missing fields to buffered-segments and ingest-spans

- schemas/uptime-results.v1.schema.json
This adds timing and extra request detail to the uptime-results `RequestInfo` object. These fields are all optional, and can be null when provided.
Once we have this info, these fields should always be set, and if the information is not available then they should be null.
We can switch these fields over to being required once we're sending this info.
> feat(uptime): Add optional fields to the `RequestInfo` schema to track more request detail

- schemas/uptime-results.v1.schema.json
Due to how we defined some fields in the schema, the code wasn't generated correctly. Also taking the opportunity to skip allowing fields to nullable. Instead, if the field isn't available, it should just not be set, instead of being null. This aligns with sending data to EAP as well, since EAP doesn't support null attributes.
> fix(uptime): Refine new fields on the `uptime-results` schema

- CODEOWNERS
- topics/taskworker-buffer-dlq.yaml
- topics/taskworker-buffer.yaml
We need to split buffers out into a separate processing pool.
Refs getsentry/taskbroker#431
> feat(taskworker) Add new topic for buffer tasks

- topics/snuba-items.yaml
Add `LogAppendTime` to `snuba-items` since this should have been here when the topic created (like `snuba-spans`)
> ref(snuba-items): add LogAppendTime to snuba-items topic

- CODEOWNERS
- topics/taskworker-ingest-errors-postprocess-dlq.yaml
- topics/taskworker-ingest-errors-postprocess.yaml
The issues team has requested that post_process_group be operated independently of other error tasks.
Refs getsentry/taskbroker#445
> feat(tasks) Add taskworker-ingest-errors-postprocess topics

- schemas/buffered-segments.v1.schema.json
I added this schema in https://github.com/getsentry/sentry-kafka-schemas/pull/422, but it was not correct! The serde definition for the `attributes` field [in Relay](https://github.com/getsentry/relay/blob/995bcfda4079a9f6f944c14e0953391fdddca270/relay-server/src/services/store.rs#L1729) does not include `skip_serializing_if = "Option::is_none"`, so span link `attributes` can in fact be `null`! I'm not sure why this happens in reality, but it seems like at least _some_ SDKs send this, the error can be seen [in production](https://sentry.sentry.io/issues/6765774441).
While I update the code to handle this case, I'm also updating the schema to match reality.
> feat(otlp): Allow span link attributes to be `null`

- schemas/buffered-segments.v1.schema.json
A new field will be sent from Relay with the downsampled retention. This is needed since we'll expect this new field.
> chore(span-buffer): Add downsampled_retention_days to the SegmentSpan schema

- schemas/buffered-segments.v1.schema.json
- schemas/ingest-spans.v1.schema.json
Relay will continue to output the `segment_id` for spans where it can be known
ahead of time. This especially is the case for spans from transaction events.
> feat(ingest-spans): Add segment_id to spans

- scripts/json_schema_changes.py
I've been asked twice by different ppl why a schema is breaking, and it
seems that the message is too dense or poorly formatted to drive the
point home. Expand details and hope that helps
> ref(schemas-diff): Expand details by default

- rust/lib.rs
- schemas/buffered-segments.v1.schema.json
- schemas/ingest-spans.v1.schema.json
Turns out the rust schema resolver cannot handle relative paths with a dot, see https://github.com/getsentry/sentry-kafka-schemas/pull/360.
Fix relative paths and add a line to rust tests that would have caught this.
ref: INGEST-540
> fix(spans): Fix relative paths
