CHANGELOG.md

meta: Add changelog

---

scripts/bump-version.sh

build: Add bump version script

---

python/tests/test_valid_topic_data.py
topics/events.yaml
topics/snuba-generic-metrics.yaml
topics/snuba-queries.yaml

- Description is required
- Versions numbers must be ascending, starting from 1 and not skip any numbers

test: Add more topic validation

---

Makefile
README.md
examples/events/1/null-values.json
python/generate_python_types.py
python/mypy.ini
python/requirements-build.txt
python/requirements.txt
schemas/events.v1.schema.json
schemas/snuba-generic-metrics.v1.schema.json
schemas/snuba-metrics.v1.schema.json
schemas/snuba-queries.v1.schema.json

Pin jsonschema-gentypes to a fork of ours, which includes the patches from https://github.com/camptocamp/jsonschema-gentypes/pull/415
This adds support for required properties

ref: Bump jsonschema-gentypes to fork

---

.github/workflows/ci.yml
Makefile
python/requirements-test.txt
python/tests/test_valid_topic_data.py
rust/lib.rs

Also make it so people can run `make -j2 lint` and experience the full power of using two cores at once.

fix: Split out linting for Rust

---

examples/snuba-queries/1/with-organization-id.json
schemas/snuba-queries.v1.schema.json

Context in PR description [here](https://github.com/getsentry/snuba/pull/3857).

feat(Querylog): Organization ID Field

---

examples/snuba-queries/1/rate-limited-real.json
examples/snuba-queries/1/snuba-queries1.json
schemas/snuba-queries.v1.schema.json

These are in the querylist as well as the top level schema.

fix(slo) Add the request_status / slo fields to the top level

---

examples/snuba-queries/1/with-organization-id.json

- #42 updated the required fields for Querylog schema but hadn't merged the new changes from #41 in so tests passed on the PR but not on merge to master

fix(tests): Broken Organization ID test

---

schemas/snuba-queries.v1.schema.json

Attempt to fix issues encountered in https://github.com/getsentry/snuba/pull/3897

feat(querylog): Improve schema

---

schemas/subscription-results.v1.schema.json

We only want this to ever be 3, so set this to a constant.

ref(subscription results): Make version a const

---

schemas/events.v1.schema.json

fix(events): Boolean request data

---

CODEOWNERS
topics/generic-metrics-subscription-results.yaml

Add a file for the generic metrics subscription results so we can look up the schema for that topic.

ref(metric alerts): Add generic metrics sub results

---

.github/workflows/schema-changes.yml

https://github.com/getsentry/action-migrations/pull/19

ref: Update action-migrations workflow, get rid of bogus "SQL" message

---

schemas/transactions.v1.schema.json

I copied this entirely from contexts on `events`

fix: Transactions context

---

schemas/transactions.v1.schema.json

Update to exclude stuff Snuba doesn't care about

fix(transactions): Simplify transactions "data"

---

scripts/json_schema_changes.py

Fixes the weird wording in https://github.com/getsentry/sentry-kafka-schemas/pull/102

fix: Fix wording in json-schema-diff

---

schemas/events.v1.schema.json
schemas/ingest-metrics.v1.schema.json
schemas/snuba-generic-metrics.v1.schema.json
schemas/snuba-metrics.v1.schema.json
schemas/snuba-queries.v1.schema.json
schemas/subscription-results.v1.schema.json
schemas/transactions.v1.schema.json

A few of those decisions were not made deliberately, and as explained in #114 we want to generally be liberal in accepting unknown properties.
If there are individual cases where we don't want to be forward-compatible, I think we should roll those back on a case-by-case basis.

ref: Make everything take additionalProperties

---

schemas/events.v1.schema.json
schemas/transactions.v1.schema.json

Removes "packages" since Snuba doesn't care about it

fix: Align sdk property in events and transactions

---

schemas/snuba-generic-metrics.v1.schema.json
schemas/snuba-metrics.v1.schema.json
schemas/snuba-queries.v1.schema.json
schemas/transactions.v1.schema.json

Fix some of the MessageProcessor crashes found in https://github.com/getsentry/snuba/pull/4152

fix: Random snuba crashes found by hypothesis-jsonschema

---

scripts/json_schema_changes.py

forwards-compatible means consumers can accept messages intended for a
future version of themselves.

fix: Fix typo in json_schema_changes

---

.github/workflows/ci.yml

Committed via https://github.com/asottile/all-repos

ref: reference SENTRY_INTERNAL_APP_ID from vars

---

.github/workflows/schema-changes.yml

This release contains a lot of changes, most importantly for us the
change to support required properties.

ref: Bump json-schema-diff

---

schemas/events.v1.schema.json

We are receiving additional properties inside the error

fix: Fix events schema

---

README.md

Many people haven't generated schemas before or don't want to write by hand. Should we recommned a tool to make the process faster?

docs: Should we recommend a tool?

---

examples/generic-events/1/generic.json
examples/generic-events/1/insert.json
schemas/generic-events.v1.schema.json

We see a "generic" event type here too. Also added an example.

fix(generic-events): There is also a generic type

---

schemas/transactions.v1.schema.json

Adding this field for the transactions SLO

fix(transactions): Make received field required for transactions

---

schemas/snuba-queries.v1.schema.json

feat: Export timer data type from querylog

---

examples/snuba-spans/1/basic_span.json
schemas/snuba-spans.v1.schema.json

First, we need to merge and deploy https://github.com/getsentry/sentry/pull/56362.

fix(spans): Fix schema as tags can only be stored as strings

---

examples/snuba-spans/1/basic_span.json
schemas/snuba-spans.v1.schema.json

Add profile_id hex string to spans

Add profile id to spans

---

python/tests/test_valid_schemas.py
schemas/snuba-queries.v1.schema.json

Changes required to get https://github.com/getsentry/snuba/pull/5402 to
pass

ref: Fix querylog schema

---

schemas/profile-functions.v1.schema.json
schemas/profile-metadata.v1.schema.json

https://github.com/getsentry/snuba/pull/5438

ref(profiles): Make schema stricter to reflect Rust consumer struct

---

topics/snuba-spans.yaml

SBC is now reading this topic to ingest data in BigQuery.

add sbc spans

---

docs/source/generate_services.py
python/generate_python_types.py
python/sentry_kafka_schemas/sentry_kafka_schemas.py
python/tests/test_examples.py
python/tests/test_valid_schemas.py
scripts/json_schema_changes.py

So it can be used to fetch the list of topics to be created

feat: Expose list_topics function

---

python/sentry_kafka_schemas/__init__.py

So it can be used to create all topics

feat: Export list_topics

---

CODEOWNERS

Switch workflow team for issues team

---

topics/ingest-feedback-events.yaml

ref: Add compression.type to ingest-feedback-events

---

CODEOWNERS
examples/monitors-clock-tasks/1/mark_missing.json
examples/monitors-clock-tasks/1/mark_timeout.json
schemas/monitors-clock-tasks.v1.schema.json
topics/monitors-clock-tasks.yaml

We will be using this topic for https://github.com/getsentry/sentry/issues/58410

feat(crons): Add topic to support monitor clock tasks

---

topics/outcomes-billing.yaml
topics/outcomes.yaml

this aligns outcomes and outcomes-billing topic definition with what we have in prod

set correct segment.bytes on outcomes topics

---

python/tests/test_sentry_kafka_schemas.py
topics/snuba-queries.yaml

matches the value in production

feat: snuba-queries is 50mb

---

docs/source/conf.py
docs/source/generate_services.py
pyproject.toml
python/generate_python_types.py
python/tests/test_examples.py
python/tests/test_valid_schemas.py
python/tests/test_valid_topic_data.py
scripts/json_schema_changes.py

Less important, but figure it's nice to be consistent :shrug:

ref(format): Match black config with sentry

---

schemas/uptime-results.v1.schema.json

This will produce better python types

ref(uptime): Improve uptime-results schema w/ definitions

---

topics/event-replacements.yaml

- retention should be 7 days not 1

fix event-replacements topic

---

examples/uptime-configs/1/example.msgpack
schemas/uptime-configs.v1.schema.json

fix(uptime): Fix required elements of schema to match properties

---

CODEOWNERS
topics/outcomes-billing-dlq.yaml
topics/outcomes-dlq.yaml

Adding schemas for https://github.com/getsentry/sentry/pull/73334

chore(billing): Add DLQ schemas

---

schemas/uptime-configs.v1.schema.json

Changing the definition so that we get nicer generated code

chore(uptime): Improve generated schema for uptime region configs

---

CODEOWNERS

Relates to:
* https://github.com/getsentry/security-as-code/pull/1174

codeowners replay backend

---

examples/snuba-uptime-results/1/failure.json
examples/snuba-uptime-results/1/success.json
examples/snuba-uptime-results/1/timeout.json
schemas/snuba-uptime-results.v1.schema.json

see https://github.com/getsentry/sentry/pull/83349

ref(uptime): remove region_slug from schema

---

schemas/events.v1.schema.json

Ref: https://github.com/getsentry/team-replay/issues/520

Add feature flag context

---

schemas/ingest-monitors.v1.schema.json

Reverts getsentry/sentry-kafka-schemas#372

Revert "fill out type for MonitorCheckIn.payload"

---

schemas/uptime-results.v1.schema.json

adds `tls_error` and `connection_error` new failure types

feat(uptime): add new failure types

---

schemas/events.v1.schema.json

This reverts commit 022a1dcfeff818719e9c5f4a45a96f811550e63f.

Revert "Add feature flag context (#364)"

---

Cargo.toml

bump sentry protos to get https://github.com/getsentry/sentry-protos/pull/110

fix: bump sentry-protos

---

schemas/events.v1.schema.json

Added "symbolicated_in_app" boolean nullable field to ErrorData
linked issue: #397

chore(sourcemaps) - Update ErrorDate kafka schema

---

CODEOWNERS
topics/taskworker-control-dlq.yaml
topics/taskworker-control.yaml
topics/taskworker-dlq.yaml
topics/taskworker-ingest-dlq.yaml

This PR is responsible for creating the default topic configs for taskworker control.

feat(taskworker): Add taskworker control and dlq topic configurations

---

CODEOWNERS
topics/taskworker-ingest-errors-dlq.yaml
topics/taskworker-ingest-errors.yaml

This PR is responsible for creating the default topic configs for ingest-errors. We plan to use this topic for taskbrokers in environments like customer-4, US, and DE

feat(taskbroker): Add ingest errors topic config

---

rust/build.rs

We used the resource name to look into `PROTOS`, using `binary_search_by_key`, and this function needs the list to be sorted.
Problem is, we were sorting by topic, and looking by resource name, so we ended up not finding the right entry.
This will fix the problem by sorting by resource name before we write the `PROTOS` slice to the file.

fix: Sort slice by resource instead of topic

---

CODEOWNERS
python/tests/test_valid_topic_data.py
topics/snuba-dead-letter-items.yaml

this is the topic definition for a new dlq on snuba-items consumer

feat: snuba-items items dlq topic definition

---

examples/preprod-artifact-events/1/basic_preprod_artifact_event.json
schemas/preprod-artifact-events.v1.schema.json

Adds an optional `requested_features` string array field to our schema so we can control which analysis features to run.
edit: see my comment below about the flagged breaking change

feat(preprod): add requested_features field to PreprodArtifact event schema
